export const REGISTER = "REGISTER";
export const SEND_REGISTRATION_REQUEST = "SEND_REGISTRATION_REQUEST";
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
export const REGISTRATION_ERROR = "REGISTRATION_ERROR";
