export const SEND_REGISTRATION_REQUEST = "SEND_REGISTRATION_REQUEST";
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
export const REGISTRATION_ERROR = "REGISTRATION_ERROR";

export const SEND_LOGIN_REQUEST = "SEND_LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const SEND_SIGN_OUT_REQUEST = "SEND_SIGN_OUT_REQUEST";
export const SIGN_OUT_ERROR = "SIGN_OUT_ERROR";
export const SIGN_OUT_SUCCESS = "SIGN_OUT_SUCCESS";

export const SEND_GET_USER_REQUEST = "SEND_GET_USER_REQUEST";
export const GET_USER_ERROR = "GET_USER_ERROR";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
