export const SEND_INGREDIENTS_REQUEST: "SEND_INGREDIENTS_REQUEST" = "SEND_INGREDIENTS_REQUEST";
export const LOAD_INGREDIENTS_SUCCESS: "LOAD_INGREDIENTS_SUCCESS" = "LOAD_INGREDIENTS_SUCCESS";
export const LOAD_INGREDIENTS_ERROR: "LOAD_INGREDIENTS_FAILED" = "LOAD_INGREDIENTS_FAILED";

export const INCREASE_INGREDIENT_COUNTER: "INCREASE_INGREDIENT_COUNTER" = "INCREASE_INGREDIENT_COUNTER";
export const DECREASE_INGREDIENT_COUNTER: "DECREASE_INGREDIENT_COUNTER" = "DECREASE_INGREDIENT_COUNTER";

export const RESET_PREVIOUS_BUNS: "RESET_PREVIOUS_BUNS" = "RESET_PREVIOUS_BUNS";
