export const ADD_MAIN_INGREDIENT: "ADD_MAIN_INGREDIENT" = "ADD_MAIN_INGREDIENT";
export const DELETE_INGREDIENT: "DELETE_INGREDIENT" = "DELETE_INGREDIENT";
export const ADD_BUNS: "ADD_BUNS" = "ADD_BUNS";
export const CHANGE_INGREDIENT_POSITION: "CHANGE_INGREDIENT_POSITION" = "CHANGE_INGREDIENT_POSITION";
export const CLEAR_CONSTRUCTOR: "CLEAR_CONSTRUCTOR" = "CLEAR_CONSTRUCTOR";
