export const OPEN_ORDER_DETAILS_MODAL: "OPEN_ORDER_DETAILS_MODAL" = "OPEN_ORDER_DETAILS_MODAL";
export const CLOSE_ORDER_DETAILS_MODAL: "CLOSE_ORDER_DETAILS_MODAL" = "CLOSE_ORDER_DETAILS_MODAL";

export const SEND_ORDER_REQUEST: "SEND_ORDER_REQUEST" = "SEND_ORDER_REQUEST";
export const GET_ORDER_DATA_SUCCESS: "GET_ORDER_DATA_SUCCESS" = "GET_ORDER_DATA_SUCCESS";
export const GET_ORDER_DATA_ERROR: "GET_ORDER_DATA_FAILED" = "GET_ORDER_DATA_FAILED";
